import 'dart:async';

import '../models/health_measurement.dart';
import '../models/health_metric_type.dart';
import '../watch_bridge/watch_health_bridge.dart';
import 'health_repository.dart';

/// [HealthRepository] backed by a real Galaxy Watch via the Samsung Health Sensor SDK
/// (v1.4.1) and Wear OS Data Layer bridge.
///
/// SDK & Data Architecture:
/// - Real-time continuous sensor readings are generated by the Samsung Health Sensor SDK
///   on the Wear OS watch app.
/// - Received [HealthMeasurement] records stream into this repository via [WatchHealthBridge].
/// - This repository maintains an in-memory chronological time series (newest-first, bounded).
/// - If no data is available (e.g. before initial sensor read), [getLatestMeasurement]
///   returns `null` and [getMeasurementHistory] returns `[]` — strictly **zero synthetic backfill**.
/// - Emits real-time updates through [watchLatestMeasurement] and [watchMeasurementHistory].
class SamsungHealthRepository implements HealthRepository {
  SamsungHealthRepository({
    WatchHealthBridge? bridge,
    Stream<HealthMeasurement>? dataStream,
    this._maxHistorySize = 100,
  }) {
    final stream = dataStream ?? bridge?.healthDataStream();
    if (stream != null) {
      _subscription = stream.listen(_onMeasurementReceived);
    }
  }

  final int _maxHistorySize;
  StreamSubscription<HealthMeasurement>? _subscription;
  final _changeStreamController = StreamController<HealthMeasurement>.broadcast();

  final Map<HealthMetricType, List<HealthMeasurement>> _history = {
    HealthMetricType.heartRate: [],
    HealthMetricType.steps: [],
  };

  void _onMeasurementReceived(HealthMeasurement measurement) {
    recordMeasurement(measurement);
  }

  /// Records a real measurement into chronological history (newest-first) and notifies listeners.
  void recordMeasurement(HealthMeasurement measurement) {
    final list = _history.putIfAbsent(measurement.type, () => []);
    list.insert(0, measurement);
    if (list.length > _maxHistorySize) {
      list.removeRange(_maxHistorySize, list.length);
    }
    if (!_changeStreamController.isClosed) {
      _changeStreamController.add(measurement);
    }
  }

  @override
  Future<HealthMeasurement?> getLatestMeasurement(
    HealthMetricType type,
  ) async {
    final list = _history[type];
    if (list == null || list.isEmpty) {
      return null;
    }
    return list.first;
  }

  @override
  Future<List<HealthMeasurement>> getMeasurementHistory(
    HealthMetricType type, {
    int limit = 50,
  }) async {
    final list = _history[type];
    if (list == null || list.isEmpty) {
      return const [];
    }
    return list.take(limit).toList();
  }

  @override
  Stream<HealthMeasurement?> watchLatestMeasurement(
    HealthMetricType type,
  ) async* {
    yield await getLatestMeasurement(type);
    yield* _changeStreamController.stream
        .where((m) => m.type == type)
        .asyncMap((_) => getLatestMeasurement(type));
  }

  @override
  Stream<List<HealthMeasurement>> watchMeasurementHistory(
    HealthMetricType type, {
    int limit = 50,
  }) async* {
    yield await getMeasurementHistory(type, limit: limit);
    yield* _changeStreamController.stream
        .where((m) => m.type == type)
        .asyncMap((_) => getMeasurementHistory(type, limit: limit));
  }

  /// Disposes stream subscriptions and controller.
  void dispose() {
    _subscription?.cancel();
    _subscription = null;
    _changeStreamController.close();
  }
}
