import 'dart:async';

import '../../analytics/data_quality_engine.dart';
import '../local/health_database.dart';
import '../models/activity_state.dart';
import '../models/health_measurement.dart';
import '../models/health_metric_type.dart';
import '../watch_bridge/watch_health_bridge.dart';
import 'health_repository.dart';

/// [HealthRepository] backed by a real Galaxy Watch via the Samsung Health Sensor SDK
/// (v1.4.1), Wear OS Data Layer bridge, and local SQLite persistence.
///
/// SDK & Data Architecture:
/// - Real-time continuous sensor readings are generated by the Samsung Health Sensor SDK
///   on the Wear OS watch app.
/// - Received [HealthMeasurement] records stream into this repository via [WatchHealthBridge].
/// - Incoming physical measurements are assessed and enriched by [DataQualityEngine]
///   using real signal characteristics (variance, jumps, sampling cadence, continuity).
/// - Enriched measurements are committed asynchronously to [HealthDatabase] (SQLite)
///   without blocking the 60fps UI rendering or stream processing.
/// - On startup, existing measurements are restored from [HealthDatabase] so history
///   survives app restarts.
/// - If no data is available, [getLatestMeasurement] returns `null` and [getMeasurementHistory]
///   returns `[]` — strictly **zero synthetic backfill**.
/// - Emits real-time updates through [watchLatestMeasurement] and [watchMeasurementHistory].
class SamsungHealthRepository implements HealthRepository {
  SamsungHealthRepository({
    WatchHealthBridge? bridge,
    Stream<HealthMeasurement>? dataStream,
    HealthDatabase? database,
    this._qualityEngine = const DataQualityEngine(),
    this._maxHistorySize = 100,
  }) : _database = database ?? HealthDatabase() {
    _initFromStorage();
    final stream = dataStream ?? bridge?.healthDataStream();
    if (stream != null) {
      _subscription = stream.listen(_onMeasurementReceived);
    }
  }

  final int _maxHistorySize;
  final DataQualityEngine _qualityEngine;
  final HealthDatabase _database;
  StreamSubscription<HealthMeasurement>? _subscription;
  final _changeStreamController = StreamController<HealthMeasurement>.broadcast();

  final Map<HealthMetricType, List<HealthMeasurement>> _history = {
    HealthMetricType.heartRate: [],
    HealthMetricType.steps: [],
    HealthMetricType.spo2: [],
  };

  void _initFromStorage() {
    // Asynchronously preload cached history from SQLite into memory
    for (final type in HealthMetricType.values) {
      _database.getMeasurements(type, limit: _maxHistorySize).then((cached) {
        if (cached.isNotEmpty) {
          final list = _history.putIfAbsent(type, () => []);
          if (list.isEmpty) {
            list.addAll(cached);
            if (!_changeStreamController.isClosed && cached.isNotEmpty) {
              _changeStreamController.add(cached.first);
            }
          }
        }
      }).catchError((_) {
        // Storage preload failure is swallowed gracefully to never crash repository
      });
    }
  }

  void _onMeasurementReceived(HealthMeasurement measurement) {
    recordMeasurement(measurement);
  }

  /// Records a real measurement into chronological history (newest-first) and notifies listeners.
  /// Automatically computes real quality and confidence via [DataQualityEngine] and
  /// asynchronously persists the record to SQLite without blocking UI streams.
  void recordMeasurement(HealthMeasurement measurement) {
    final list = _history.putIfAbsent(measurement.type, () => []);

    // Enrich measurement with real mathematical data quality assessment
    final enriched = _qualityEngine.enrich(measurement, list);

    list.insert(0, enriched);
    if (list.length > _maxHistorySize) {
      list.removeRange(_maxHistorySize, list.length);
    }
    if (!_changeStreamController.isClosed) {
      _changeStreamController.add(enriched);
    }

    // Asynchronous non-blocking persistence
    _database.insertMeasurement(enriched).catchError((_) {});
  }

  @override
  Future<HealthMeasurement?> getLatestMeasurement(
    HealthMetricType type,
  ) async {
    final list = _history[type];
    if (list != null && list.isNotEmpty) {
      return list.first;
    }
    return await _database.getLatestMeasurement(type);
  }

  @override
  Future<List<HealthMeasurement>> getMeasurementHistory(
    HealthMetricType type, {
    int limit = 50,
  }) async {
    final list = _history[type];
    if (list != null && list.isNotEmpty) {
      return list.take(limit).toList();
    }
    return await _database.getMeasurements(type, limit: limit);
  }

  @override
  Future<List<HealthMeasurement>> getMeasurementsInRange(
    HealthMetricType type, {
    DateTime? startTime,
    DateTime? endTime,
    ActivityState? activityState,
    double? minQualityScore,
    int? limit,
  }) async {
    return await _database.getMeasurements(
      type,
      startTime: startTime,
      endTime: endTime,
      activityState: activityState,
      minQualityScore: minQualityScore,
      limit: limit,
    );
  }

  @override
  Stream<HealthMeasurement?> watchLatestMeasurement(
    HealthMetricType type,
  ) async* {
    yield await getLatestMeasurement(type);
    yield* _changeStreamController.stream
        .where((m) => m.type == type)
        .asyncMap((_) => getLatestMeasurement(type));
  }

  @override
  Stream<List<HealthMeasurement>> watchMeasurementHistory(
    HealthMetricType type, {
    int limit = 50,
  }) async* {
    yield await getMeasurementHistory(type, limit: limit);
    yield* _changeStreamController.stream
        .where((m) => m.type == type)
        .asyncMap((_) => getMeasurementHistory(type, limit: limit));
  }

  /// Disposes stream subscriptions and controller.
  void dispose() {
    _subscription?.cancel();
    _subscription = null;
    _changeStreamController.close();
  }
}
